import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>


        {children}
        
        {/* <footer className="bg-verde-spotify w-screen py-3">
        DESARROLLADO POR ESTUDIANTES DE LA FACULTAD DE INGENIERÍA DE SISTEMAS DE LA
        <b>UNIVERSIDAD NACIONAL DE CAÑETE</b>
        </footer> */}
        
      </body>
    </html>
  );
}
